import type { KnowledgeBaseEntry } from '@/types';

const generateId = () => Math.random().toString(36).substr(2, 9);

const now = Date.now();

export const sampleKnowledgeBaseData: KnowledgeBaseEntry[] = [
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'erlitou-2024-1',
    sourceProjectName: '二里头遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '二里头遗址',
      archaeologist: '张教授',
      excavationDate: '2024-03',
      description: '二里头遗址是中国最早的都邑遗址之一，发现了大量夏代晚期的陶器群',
    },
    title: '复原方案：二里头夏代晚期陶罐',
    description: '二里头遗址出土的夏代晚期陶罐，具有典型的夏代陶器特征',
    createdAt: now - 86400000 * 30,
    importedAt: now - 86400000 * 20,
    tags: ['罐', '夏', '二里头', '绳纹', '敛口'],
    featureVector: {
      artifactType: 'jar',
      period: '夏',
      dynasty: '夏',
      layerNumber: '3',
      patternStyle: 'string',
      thickness: 8,
      rimCurvature: 'slightly_inward',
      estimatedRimDiameter: 22,
      estimatedHeight: 28,
      wallThickness: 8,
    },
    isTrusted: true,
    viewCount: 156,
    referenceCount: 23,
    schemeMetrics: {
      estimatedRimDiameter: 22,
      estimatedHeight: 28,
      estimatedBaseDiameter: 12,
      estimatedWallThickness: 8,
      matchScore: 92,
      thicknessConsistencyScore: 88,
      patternAlignmentScore: 95,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 45,
    },
  },
  {
    id: generateId(),
    entryType: 'sherd',
    sourceProjectId: 'erlitou-2024-1',
    sourceProjectName: '二里头遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '二里头遗址',
      archaeologist: '张教授',
      excavationDate: '2024-03',
    },
    title: '残片 SH-023',
    description: '二里头遗址第3层出土的陶罐口沿残片，绳纹纹饰清晰',
    createdAt: now - 86400000 * 28,
    importedAt: now - 86400000 * 18,
    tags: ['罐', '夏', '二里头', '绳纹', '残片'],
    featureVector: {
      artifactType: 'jar',
      period: '夏',
      dynasty: '夏',
      layerNumber: '3',
      patternStyle: 'string',
      thickness: 8.2,
      rimCurvature: 'slightly_inward',
      estimatedRimDiameter: null,
      estimatedHeight: null,
      wallThickness: 8.2,
    },
    isTrusted: true,
    viewCount: 89,
    referenceCount: 12,
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'yinxu-2023-1',
    sourceProjectName: '殷墟遗址2023年发掘项目',
    sourceProjectMetadata: {
      siteName: '殷墟遗址',
      archaeologist: '李研究员',
      excavationDate: '2023-09',
      description: '殷墟商代晚期都城遗址，出土了大量精美的商代青铜器和陶器',
    },
    title: '复原方案：殷墟商代晚期陶甗',
    description: '殷墟遗址出土的商代晚期陶甗，是商代典型的炊器组合',
    createdAt: now - 86400000 * 100,
    importedAt: now - 86400000 * 50,
    tags: ['甗', '商', '殷墟', '弦纹', '微撇'],
    featureVector: {
      artifactType: 'pot',
      period: '商',
      dynasty: '商',
      layerNumber: '2',
      patternStyle: 'cord',
      thickness: 6.5,
      rimCurvature: 'slightly_outward',
      estimatedRimDiameter: 28,
      estimatedHeight: 42,
      wallThickness: 6.5,
    },
    isTrusted: true,
    viewCount: 234,
    referenceCount: 45,
    schemeMetrics: {
      estimatedRimDiameter: 28,
      estimatedHeight: 42,
      estimatedBaseDiameter: 15,
      estimatedWallThickness: 6.5,
      matchScore: 96,
      thicknessConsistencyScore: 91,
      patternAlignmentScore: 94,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 52,
    },
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'yangshao-2022-1',
    sourceProjectName: '仰韶文化半坡遗址2022年发掘项目',
    sourceProjectMetadata: {
      siteName: '半坡遗址',
      archaeologist: '王教授',
      excavationDate: '2022-05',
      description: '仰韶文化半坡类型遗址，以彩陶闻名于世',
    },
    title: '复原方案：仰韶文化彩陶盆',
    description: '半坡遗址出土的仰韶文化彩陶盆，内壁绘有精美的几何纹饰',
    createdAt: now - 86400000 * 200,
    importedAt: now - 86400000 * 120,
    tags: ['盆', '新石器时代', '仰韶', '彩绘', '几何纹', '微敛'],
    featureVector: {
      artifactType: 'bowl',
      period: '新石器时代',
      dynasty: null,
      layerNumber: '4',
      patternStyle: 'painted',
      thickness: 5,
      rimCurvature: 'slightly_inward',
      estimatedRimDiameter: 32,
      estimatedHeight: 16,
      wallThickness: 5,
    },
    isTrusted: true,
    viewCount: 445,
    referenceCount: 78,
    schemeMetrics: {
      estimatedRimDiameter: 32,
      estimatedHeight: 16,
      estimatedBaseDiameter: 14,
      estimatedWallThickness: 5,
      matchScore: 98,
      thicknessConsistencyScore: 95,
      patternAlignmentScore: 97,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 38,
    },
  },
  {
    id: generateId(),
    entryType: 'evidence_chain',
    sourceProjectId: 'yangshao-2022-1',
    sourceProjectName: '仰韶文化半坡遗址2022年发掘项目',
    sourceProjectMetadata: {
      siteName: '半坡遗址',
      archaeologist: '王教授',
      excavationDate: '2022-05',
    },
    title: '仰韶文化彩陶盆证据链',
    description: '包含地层学、类型学、碳十四测年等多源证据链',
    createdAt: now - 86400000 * 190,
    importedAt: now - 86400000 * 115,
    tags: ['证据链', '新石器时代', '仰韶', '彩陶盆'],
    featureVector: {
      artifactType: 'bowl',
      period: '新石器时代',
      dynasty: null,
      layerNumber: '4',
      patternStyle: 'painted',
      thickness: null,
      rimCurvature: null,
      estimatedRimDiameter: null,
      estimatedHeight: null,
      wallThickness: null,
    },
    isTrusted: true,
    viewCount: 167,
    referenceCount: 34,
    evidenceChain: {
      evidenceSources: [
        {
          id: generateId(),
          type: 'scientific',
          title: '碳十四测年报告',
          description: '加速器质谱碳十四测年结果显示距今约6000年',
          author: '碳十四实验室',
          publicationDate: '2022-08-15',
        },
        {
          id: generateId(),
          type: 'stratigraphy',
          title: '地层学分析报告',
          description: '出土于第4文化层，属于仰韶文化早期堆积',
          author: '王教授',
          publicationDate: '2022-07-20',
        },
      ],
      chronologyJudgments: [
        {
          id: generateId(),
          period: '新石器时代',
          confidenceLevel: 'very_high',
          basis: '碳十四测年与地层学证据相互印证',
          evidenceSourceIds: [],
          createdAt: now - 86400000 * 190,
          createdBy: '王教授',
        },
      ],
      stratigraphyInfos: [
        {
          id: generateId(),
          layerNumber: '4',
          layerDescription: '仰韶文化早期文化层，厚约1.2米',
          depthFrom: 2.8,
          depthTo: 4.0,
          confidenceLevel: 'high',
          evidenceSourceIds: [],
          createdAt: now - 86400000 * 190,
          createdBy: '王教授',
        },
      ],
      referenceArtifacts: [
        {
          id: generateId(),
          artifactName: '半坡类型彩陶盆',
          artifactType: '彩陶盆',
          museumOrCollection: '陕西历史博物馆',
          similarityDescription: '器型、纹饰风格完全一致',
          similarityScore: 98,
          confidenceLevel: 'very_high',
          evidenceSourceIds: [],
          createdAt: now - 86400000 * 190,
          createdBy: '王教授',
        },
      ],
      expertOpinions: [
        {
          id: generateId(),
          expertName: '苏秉琦',
          expertTitle: '考古学泰斗',
          institution: '中国社会科学院考古研究所',
          opinionType: 'support',
          content: '此件彩陶盆是仰韶文化半坡类型的标准器型，具有重要的学术价值。',
          confidenceLevel: 'very_high',
          evidenceSourceIds: [],
          createdAt: now - 86400000 * 185,
        },
      ],
    },
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'longshan-2023-1',
    sourceProjectName: '龙山文化城子崖遗址2023年发掘项目',
    sourceProjectMetadata: {
      siteName: '城子崖遗址',
      archaeologist: '刘研究员',
      excavationDate: '2023-04',
      description: '龙山文化的代表性遗址，以黑陶为主要特征',
    },
    title: '复原方案：龙山文化黑陶杯',
    description: '城子崖遗址出土的龙山文化蛋壳黑陶杯，器壁薄如蛋壳，是龙山文化制陶工艺的巅峰之作',
    createdAt: now - 86400000 * 150,
    importedAt: now - 86400000 * 80,
    tags: ['杯', '新石器时代', '龙山', '素面', '蛋壳黑陶', '直口'],
    featureVector: {
      artifactType: 'cup',
      period: '新石器时代',
      dynasty: null,
      layerNumber: '2',
      patternStyle: 'plain',
      thickness: 1.5,
      rimCurvature: 'straight',
      estimatedRimDiameter: 8,
      estimatedHeight: 12,
      wallThickness: 1.5,
    },
    isTrusted: true,
    viewCount: 312,
    referenceCount: 56,
    schemeMetrics: {
      estimatedRimDiameter: 8,
      estimatedHeight: 12,
      estimatedBaseDiameter: 4,
      estimatedWallThickness: 1.5,
      matchScore: 94,
      thicknessConsistencyScore: 97,
      patternAlignmentScore: 100,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 41,
    },
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'zhouyuan-2024-1',
    sourceProjectName: '周原遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '周原遗址',
      archaeologist: '陈教授',
      excavationDate: '2024-06',
      description: '周人发祥地，西周时期的重要都邑遗址',
    },
    title: '复原方案：西周青铜纹鼎',
    description: '周原遗址出土的西周早期青铜纹鼎，是西周青铜礼器的典型代表',
    createdAt: now - 86400000 * 60,
    importedAt: now - 86400000 * 25,
    tags: ['鼎', '西周', '周原', '饕餮纹', '微撇'],
    featureVector: {
      artifactType: 'tripod',
      period: '西周',
      dynasty: '周',
      layerNumber: '1',
      patternStyle: 'carved',
      thickness: 12,
      rimCurvature: 'slightly_outward',
      estimatedRimDiameter: 36,
      estimatedHeight: 48,
      wallThickness: 12,
    },
    isTrusted: true,
    viewCount: 178,
    referenceCount: 29,
    schemeMetrics: {
      estimatedRimDiameter: 36,
      estimatedHeight: 48,
      estimatedBaseDiameter: 22,
      estimatedWallThickness: 12,
      matchScore: 91,
      thicknessConsistencyScore: 89,
      patternAlignmentScore: 93,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 55,
    },
  },
  {
    id: generateId(),
    entryType: 'sherd',
    sourceProjectId: 'zhouyuan-2024-1',
    sourceProjectName: '周原遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '周原遗址',
      archaeologist: '陈教授',
      excavationDate: '2024-06',
    },
    title: '残片 SH-008',
    description: '周原遗址第1层出土的陶鼎腹部残片，饰有饕餮纹残迹',
    createdAt: now - 86400000 * 55,
    importedAt: now - 86400000 * 22,
    tags: ['鼎', '西周', '周原', '雕刻', '残片'],
    featureVector: {
      artifactType: 'tripod',
      period: '西周',
      dynasty: '周',
      layerNumber: '1',
      patternStyle: 'carved',
      thickness: 12,
      rimCurvature: null,
      estimatedRimDiameter: null,
      estimatedHeight: null,
      wallThickness: 12,
    },
    isTrusted: false,
    viewCount: 45,
    referenceCount: 8,
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'han-dynasty-2023-1',
    sourceProjectName: '汉代长沙王陵2023年发掘项目',
    sourceProjectMetadata: {
      siteName: '长沙王陵墓',
      archaeologist: '赵研究员',
      excavationDate: '2023-11',
      description: '西汉时期长沙王的陵墓，出土了大量精美漆器和陶器',
    },
    title: '复原方案：汉代彩绘陶壶',
    description: '长沙王陵出土的西汉彩绘陶壶，壶身绘有云气纹和神兽图案',
    createdAt: now - 86400000 * 90,
    importedAt: now - 86400000 * 40,
    tags: ['壶', '汉', '长沙', '彩绘', '花卉纹', '敞口'],
    featureVector: {
      artifactType: 'vase',
      period: '汉',
      dynasty: '汉',
      layerNumber: '1',
      patternStyle: 'floral',
      thickness: 7,
      rimCurvature: 'flared',
      estimatedRimDiameter: 18,
      estimatedHeight: 35,
      wallThickness: 7,
    },
    isTrusted: true,
    viewCount: 267,
    referenceCount: 51,
    schemeMetrics: {
      estimatedRimDiameter: 18,
      estimatedHeight: 35,
      estimatedBaseDiameter: 11,
      estimatedWallThickness: 7,
      matchScore: 93,
      thicknessConsistencyScore: 90,
      patternAlignmentScore: 96,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 48,
    },
  },
  {
    id: generateId(),
    entryType: 'report',
    sourceProjectId: 'han-dynasty-2023-1',
    sourceProjectName: '汉代长沙王陵2023年发掘项目',
    sourceProjectMetadata: {
      siteName: '长沙王陵墓',
      archaeologist: '赵研究员',
      excavationDate: '2023-11',
    },
    title: '报告：汉代彩绘陶壶复原研究报告',
    description: '对长沙王陵出土彩绘陶壶的详细复原研究报告，包含形制分析、纹饰研究、工艺研究等内容',
    createdAt: now - 86400000 * 80,
    importedAt: now - 86400000 * 35,
    tags: ['报告', '汉', '长沙', '陶壶', '研究报告'],
    featureVector: {
      artifactType: null,
      period: '汉',
      dynasty: '汉',
      layerNumber: null,
      patternStyle: null,
      thickness: null,
      rimCurvature: null,
      estimatedRimDiameter: null,
      estimatedHeight: null,
      wallThickness: null,
    },
    isTrusted: true,
    viewCount: 134,
    referenceCount: 41,
    report: {
      id: generateId(),
      generatedAt: now - 86400000 * 80,
      generatedBy: '赵研究员',
      format: 'pdf',
      projectName: '汉代长沙王陵2023年发掘项目',
      schemeName: '汉代彩绘陶壶',
      schemeId: generateId(),
      content: '',
      metadata: {
        version: '1.0.0',
        sherdCount: 5,
        evidenceCount: 12,
        expertOpinionCount: 3,
        chronologyCount: 2,
        stratigraphyCount: 1,
        referenceCount: 4,
      },
    },
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'tang-dynasty-2024-1',
    sourceProjectName: '唐代大明宫遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '大明宫遗址',
      archaeologist: '孙教授',
      excavationDate: '2024-02',
      description: '唐代大明宫是唐代长安城的皇宫，出土了大量宫廷用瓷',
    },
    title: '复原方案：唐三彩盘',
    description: '大明宫遗址出土的唐三彩盘，是唐代宫廷用瓷的代表',
    createdAt: now - 86400000 * 45,
    importedAt: now - 86400000 * 15,
    tags: ['盘', '唐', '大明宫', '三彩', '花卉纹', '敞口'],
    featureVector: {
      artifactType: 'plate',
      period: '唐',
      dynasty: '唐',
      layerNumber: '2',
      patternStyle: 'floral',
      thickness: 4,
      rimCurvature: 'flared',
      estimatedRimDiameter: 25,
      estimatedHeight: 5,
      wallThickness: 4,
    },
    isTrusted: true,
    viewCount: 289,
    referenceCount: 67,
    schemeMetrics: {
      estimatedRimDiameter: 25,
      estimatedHeight: 5,
      estimatedBaseDiameter: 12,
      estimatedWallThickness: 4,
      matchScore: 95,
      thicknessConsistencyScore: 92,
      patternAlignmentScore: 98,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 43,
    },
  },
  {
    id: generateId(),
    entryType: 'sherd',
    sourceProjectId: 'tang-dynasty-2024-1',
    sourceProjectName: '唐代大明宫遗址2024年发掘项目',
    sourceProjectMetadata: {
      siteName: '大明宫遗址',
      archaeologist: '孙教授',
      excavationDate: '2024-02',
    },
    title: '残片 SH-041',
    description: '大明宫遗址第2层出土的三彩盘口沿残片，黄、绿、白三彩釉色鲜艳',
    createdAt: now - 86400000 * 40,
    importedAt: now - 86400000 * 12,
    tags: ['盘', '唐', '大明宫', '三彩', '花卉纹', '残片'],
    featureVector: {
      artifactType: 'plate',
      period: '唐',
      dynasty: '唐',
      layerNumber: '2',
      patternStyle: 'floral',
      thickness: 4,
      rimCurvature: 'flared',
      estimatedRimDiameter: null,
      estimatedHeight: null,
      wallThickness: 4,
    },
    isTrusted: false,
    viewCount: 76,
    referenceCount: 14,
  },
  {
    id: generateId(),
    entryType: 'scheme',
    sourceProjectId: 'song-dynasty-2023-1',
    sourceProjectName: '宋代官窑遗址2023年发掘项目',
    sourceProjectMetadata: {
      siteName: '南宋官窑遗址',
      archaeologist: '周研究员',
      excavationDate: '2023-08',
      description: '南宋时期的官窑遗址，出土了大量精美的青瓷',
    },
    title: '复原方案：南宋官窑青瓷碟',
    description: '南宋官窑遗址出土的青瓷碟，釉色莹润，是南宋青瓷的精品',
    createdAt: now - 86400000 * 75,
    importedAt: now - 86400000 * 30,
    tags: ['碟', '宋', '官窑', '素面', '微敛'],
    featureVector: {
      artifactType: 'dish',
      period: '宋',
      dynasty: '宋',
      layerNumber: '3',
      patternStyle: 'plain',
      thickness: 3,
      rimCurvature: 'slightly_inward',
      estimatedRimDiameter: 12,
      estimatedHeight: 3,
      wallThickness: 3,
    },
    isTrusted: true,
    viewCount: 198,
    referenceCount: 38,
    schemeMetrics: {
      estimatedRimDiameter: 12,
      estimatedHeight: 3,
      estimatedBaseDiameter: 6,
      estimatedWallThickness: 3,
      matchScore: 97,
      thicknessConsistencyScore: 96,
      patternAlignmentScore: 100,
      hasContourBreak: false,
      breakPoints: [],
      failureReasons: [],
      calculationTime: 36,
    },
  },
];

export function getSampleKnowledgeBase(): KnowledgeBaseEntry[] {
  return JSON.parse(JSON.stringify(sampleKnowledgeBaseData));
}
